INSERT INTO users (name, age) VALUES ("Marcos", 29);
INSERT INTO users (name, age) VALUES ("Vanessa", 25);
INSERT INTO users (name, age) VALUES ("Gabe", 9);
INSERT INTO users (name, age) VALUES ("Laya", 4);
INSERT INTO users (name, age) VALUES ("Eugenio", 58);
INSERT INTO users (name, age) VALUES ("Irene", 56);
INSERT INTO users (name, age) VALUES ("Job", 31);
INSERT INTO users (name, age) VALUES ("Paul", 26);
INSERT INTO users (name, age) VALUES ("Cynthia", 24);
INSERT INTO users (name, age) VALUES ("Isela", 18);
INSERT INTO users (name, age) VALUES ("Sonnie", 2);
INSERT INTO users (name, age) VALUES ("Fili", 50);
INSERT INTO users (name, age) VALUES ("Sandra", 50);
INSERT INTO users (name, age) VALUES ("Brian", 18);
INSERT INTO users (name, age) VALUES ("Narali", 18);
INSERT INTO users (name, age) VALUES ("Brandon", 22);
INSERT INTO users (name, age) VALUES ("kikito", 22);
INSERT INTO users (name, age) VALUES ("Rafeal", 29);
INSERT INTO users (name, age) VALUES ("Luis", 31);
INSERT INTO users (name, age) VALUES ("Cisco", 33);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Last of Us", "Drama", 2000000, "June 1st, 2020", "June 1st 2025");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Last of Us", "Drama", 2000000, "June 1st, 2020", "June 1st 2025");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Last of Us", "Drama", 2000000, "June 1st, 2020", "June 1st 2025");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Last of Us", "Drama", 2000000, "June 1st, 2020", "June 1st 2025");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Last of Us", "Drama", 2000000, "June 1st, 2020", "June 1st 2025");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Last of Us", "Drama", 2000000, "June 1st, 2020", "June 1st 2025");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Last of Us", "Drama", 2000000, "June 1st, 2020", "June 1st 2025");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Last of Us", "Drama", 2000000, "June 1st, 2020", "June 1st 2025");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Last of Us", "Drama", 2000000, "June 1st, 2020", "June 1st 2025");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The Last of Us", "Drama", 2000000, "June 1st, 2020", "June 1st 2025");

INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200000, 1, 1);